- name: docker build and push
  hosts: localhost

  tasks:
    - name: Build Docker Image
      command: docker build -t calculator.jar .
      args:
        chdir: /var/lib/jenkins/workspace/sientific_calculator 

    - name: tag image
      command: docker tag calculator.jar tezaswa/calculator:latest

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: tezaswa
        password: 915368742

    - name: push image
      command: docker push tezaswa/calculator:latest
